#!/bin/bash

SCRIPTPATH="$(
  cd "$(dirname "$0")" >/dev/null 2>&1
  pwd -P
)"

###
# Arg 1 : Command
# Arg 2 : Install script
###
print_cmd_error() {
  printf "Command not found : $1\n"
  [ ! -z "$2" ] && printf "Run this command to install : $2\n"

  exit 1
}

if ! command -v npx &>/dev/null; then
  print_cmd_error "npx"
fi

HELPTEXT="Usage :
  $0 <name> <url> -- [extra nativefier options]

  <name> : Name of the application
  <url>  : Url of the webpage to package"

if [ -z "$1" -o -z "$2" ]; then
  printf "$HELPTEXT\n"
  exit 1
fi

name="$1"
url="$2"

shift
shift
shift

(
  if [ -d "$name.AppDir" ]; then
    printf "ERROR : \`$name.AppDir\` directory already exists\n"
    exit 1
  fi
  
  npx nativefier -n "$name" -p linux "$url" $@
  mv "$name"-linux-* "$name.AppDir"
  cd "$name".AppDir/
  
  cp resources/app/icon.* ./
  
  echo "[Desktop Entry]" > $name.desktop
  echo "Name=$name" >> $name.desktop
  echo "Exec=AppRun %U" >> $name.desktop
  echo "Terminal=false" >> $name.desktop
  echo "Type=Application" >> $name.desktop
  echo "Icon=icon" >> $name.desktop
  echo "X-AppImage-Version=1.0.0" >> $name.desktop
  echo "Categories=Utility;" >> $name.desktop
  
  echo "#!/bin/bash" > AppRun
  echo "exec \$APPDIR/$name" >> AppRun
  chmod +x ./AppRun
)

[ ! -e /tmp/appimagetool ] && wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /tmp/appimagetool
chmod +x /tmp/appimagetool

/tmp/appimagetool "$name.AppDir"
